SUPPORTED_MODELS = ['rawnet3_aasist', 
                    'rawnet3_conformer',
                    'wavlmbase_aasist',
                    "lfcc_lcnn",
                    'rawnet3_serawformer',
                    'rawnet3_co_aasist',
                    'sincconv_aasist',
                    'rawnet3_serawformer_mixup',
                    'rawnet3_attentive',
                    'wavlmbase_co_aasist',
                    'wav2vec_self_vib',
                    'wav2vec_self_aasist',
                    'wav2vec2_960_vib_gelu_multi',
                    'rawnet3_hmconformer',
                    'wavlmbase_conformer',
                    'rawnet3_conformertcm',
                    'wav2vec2_960_conformertcm',
                    'wav2vec2_960_attentive',
                    'wavlmbase_conformertcm',
                    'wav2vec2_960_conformertcm',
                    'hs_conformer',
                    'wav2vec2_large_vib_gelu_multi',
                    'wav2vec2_large_conformertcm']


